In [1]:
import requests
import json
api_key=""

In [59]:
lst_dest=[]  
origin="Tel Aviv"
with open("dests.txt", "r") as destinations:  ##open the text file, and apply the loop for each city. Append all the data in the list.
    for i in destinations:
        url="https://maps.googleapis.com/maps/api/distancematrix/json?destinations=%s&origins=%s&units=imperial&key=%s" % (i.strip(),origin,api_key)
        response=requests.get(url).json()
        lst_dest.append(response)
    
lst_dest

[{'destination_addresses': ['İstanbul, Türkiye'],
  'origin_addresses': ['Tel Aviv-Yafo, Israel'],
  'rows': [{'elements': [{'distance': {'text': '1,128 mi', 'value': 1815227},
      'duration': {'text': '21 hours 3 mins', 'value': 75772},
      'status': 'OK'}]}],
  'status': 'OK'},
 {'destination_addresses': ['Amsterdam, Netherlands'],
  'origin_addresses': ['Tel Aviv-Yafo, Israel'],
  'rows': [{'elements': [{'distance': {'text': '2,816 mi', 'value': 4532541},
      'duration': {'text': '2 days 0 hours', 'value': 173011},
      'status': 'OK'}]}],
  'status': 'OK'},
 {'destination_addresses': ['Valletta, Malta'],
  'origin_addresses': ['Tel Aviv-Yafo, Israel'],
  'rows': [{'elements': [{'distance': {'text': '2,357 mi', 'value': 3792883},
      'duration': {'text': '2 days 3 hours', 'value': 183056},
      'status': 'OK'}]}],
  'status': 'OK'},
 {'destination_addresses': ['Basel, Switzerland'],
  'origin_addresses': ['Tel Aviv-Yafo, Israel'],
  'rows': [{'elements': [{'distance': {'text': '2,543 mi', 'value': 4092805},
      'duration': {'text': '1 day 20 hours', 'value': 158547},
      'status': 'OK'}]}],
  'status': 'OK'},
 {'destination_addresses': ['Doha, Qatar'],
  'origin_addresses': ['Tel Aviv-Yafo, Israel'],
  'rows': [{'elements': [{'distance': {'text': '1,345 mi', 'value': 2164477},
      'duration': {'text': '22 hours 39 mins', 'value': 81527},
      'status': 'OK'}]}],
  'status': 'OK'}]

In [69]:
long_lat_dest=[]
with open("dests.txt", "r") as destinations: ##open the text file, and apply the loop for each city. Append all the data in the list.
    for i in destinations:
        url="https://maps.googleapis.com/maps/api/geocode/json?address=%s&key=%s" % (i.strip(),api_key)
        response2=requests.get(url).json()
        long_lat_dest.append(response2)
long_lat_dest

[{'results': [{'address_components': [{'long_name': 'İstanbul',
      'short_name': 'İstanbul',
      'types': ['locality', 'political']},
     {'long_name': 'İstanbul',
      'short_name': 'İstanbul',
      'types': ['administrative_area_level_1', 'political']},
     {'long_name': 'Türkiye',
      'short_name': 'TR',
      'types': ['country', 'political']}],
    'formatted_address': 'İstanbul, Türkiye',
    'geometry': {'bounds': {'northeast': {'lat': 41.199239, 'lng': 29.4288049},
      'southwest': {'lat': 40.811404, 'lng': 28.595554}},
     'location': {'lat': 41.0082376, 'lng': 28.9783589},
     'location_type': 'APPROXIMATE',
     'viewport': {'northeast': {'lat': 41.199239, 'lng': 29.4288049},
      'southwest': {'lat': 40.811404, 'lng': 28.595554}}},
    'place_id': 'ChIJawhoAASnyhQR0LABvJj-zOE',
    'types': ['locality', 'political']}],
  'status': 'OK'},
 {'results': [{'address_components': [{'long_name': 'Amsterdam',
      'short_name': 'Amsterdam',
      'types': ['locality', 'political']},
     {'long_name': 'Government of Amsterdam',
      'short_name': 'Government of Amsterdam',
      'types': ['administrative_area_level_2', 'political']},
     {'long_name': 'North Holland',
      'short_name': 'NH',
      'types': ['administrative_area_level_1', 'political']},
     {'long_name': 'Netherlands',
      'short_name': 'NL',
      'types': ['country', 'political']}],
    'formatted_address': 'Amsterdam, Netherlands',
    'geometry': {'bounds': {'northeast': {'lat': 52.4311573, 'lng': 5.1080201},
      'southwest': {'lat': 52.27798, 'lng': 4.7287589}},
     'location': {'lat': 52.3675734, 'lng': 4.9041389},
     'location_type': 'APPROXIMATE',
     'viewport': {'northeast': {'lat': 52.4311573, 'lng': 5.1080201},
      'southwest': {'lat': 52.27798, 'lng': 4.7287589}}},
    'place_id': 'ChIJVXealLU_xkcRja_At0z9AGY',
    'types': ['locality', 'political']}],
  'status': 'OK'},
 {'results': [{'address_components': [{'long_name': 'Valletta',
      'short_name': 'Valletta',
      'types': ['locality', 'political']},
     {'long_name': 'Malta',
      'short_name': 'MT',
      'types': ['country', 'political']}],
    'formatted_address': 'Valletta, Malta',
    'geometry': {'bounds': {'northeast': {'lat': 35.9036855,
       'lng': 14.5204815},
      'southwest': {'lat': 35.8932353, 'lng': 14.5053349}},
     'location': {'lat': 35.8992375, 'lng': 14.5140996},
     'location_type': 'APPROXIMATE',
     'viewport': {'northeast': {'lat': 35.9036855, 'lng': 14.5204815},
      'southwest': {'lat': 35.8932353, 'lng': 14.5053349}}},
    'place_id': 'ChIJxUeGHShFDhMRF8lC4o7TWnQ',
    'types': ['locality', 'political']}],
  'status': 'OK'},
 {'results': [{'address_components': [{'long_name': 'Basel',
      'short_name': 'Basel',
      'types': ['locality', 'political']},
     {'long_name': 'Basel-Stadt',
      'short_name': 'Basel-Stadt',
      'types': ['administrative_area_level_2', 'political']},
     {'long_name': 'Basel City',
      'short_name': 'BS',
      'types': ['administrative_area_level_1', 'political']},
     {'long_name': 'Switzerland',
      'short_name': 'CH',
      'types': ['country', 'political']}],
    'formatted_address': 'Basel, Switzerland',
    'geometry': {'bounds': {'northeast': {'lat': 47.5899017,
       'lng': 7.634148399999999},
      'southwest': {'lat': 47.5192972, 'lng': 7.5546595}},
     'location': {'lat': 47.5595986, 'lng': 7.5885761},
     'location_type': 'APPROXIMATE',
     'viewport': {'northeast': {'lat': 47.5899017, 'lng': 7.634148399999999},
      'southwest': {'lat': 47.5192972, 'lng': 7.5546595}}},
    'place_id': 'ChIJTzBpJ8dJkEcRkIpt83DrHDY',
    'types': ['locality', 'political']}],
  'status': 'OK'},
 {'results': [{'address_components': [{'long_name': 'Doha',
      'short_name': 'Doha',
      'types': ['locality', 'political']},
     {'long_name': 'Doha',
      'short_name': 'Doha',
      'types': ['administrative_area_level_1', 'political']},
     {'long_name': 'Qatar',
      'short_name': 'QA',
      'types': ['country', 'political']}],
    'formatted_address': 'Doha, Qatar',
    'geometry': {'bounds': {'northeast': {'lat': 25.4125783,
       'lng': 51.6281212},
      'southwest': {'lat': 25.1554399, 'lng': 51.3958721}},
     'location': {'lat': 25.2854473, 'lng': 51.53103979999999},
     'location_type': 'APPROXIMATE',
     'viewport': {'northeast': {'lat': 25.4125783, 'lng': 51.6281212},
      'southwest': {'lat': 25.1554399, 'lng': 51.3958721}}},
    'place_id': 'ChIJf-jc_zTFRT4RsdTPeJ8x2UQ',
    'types': ['locality', 'political']}],
  'status': 'OK'}]

In [314]:
tar=[]
distances=[]
durations=[]
lat_long=[]
for i in lst_dest:
    distances.append(i["rows"][0]["elements"][0]["distance"]["value"]//1000)
    durations.append(i["rows"][0]["elements"][0]["duration"]["value"]) 
    tar.append(i["destination_addresses"][0])
for j in long_lat_dest:
    lat_long.append(j["results"][0]["geometry"]["location"])
lat=[]
long=[]
for i in lat_long:
    lat.append(i.get("lat"))
    long.append(i.get("lng"))

In [315]:
import pandas as pd

my_dict={"Target":tar,"Distance_km":distances,"Duration":durations,"Longitude":long,"Latitude":lat}
df=pd.DataFrame(my_dict)
df["Duration"]=df["Duration"].apply(lambda x: int(x) )  #changing the format of the duration to hours an  in only
hours=df["Duration"].apply(lambda x: x/3600)
minutes=((hours-hours//1)*60//1).astype(int)
hours=df["Duration"].apply(lambda x: x//3600)
df["Duration"]=hours.astype(str)+" hours-"+minutes.astype(str)+" min"


df

                   Target  Distance_km         Duration  Longitude   Latitude
0       İstanbul, Türkiye         1815   21 hours-2 min  28.978359  41.008238
1  Amsterdam, Netherlands         4532   48 hours-3 min   4.904139  52.367573
2         Valletta, Malta         3792  50 hours-50 min  14.514100  35.899237
3      Basel, Switzerland         4092   44 hours-2 min   7.588576  47.559599
4             Doha, Qatar         2164  22 hours-38 min  51.531040  25.285447

In [316]:
print("As we can see the 3 furthest cities from Tel Aviv are Amsterdam, Basel and Valetta ")
df.nlargest(3,"Distance_km")

As we can see the 3 furthest cities from Tel Aviv are Amsterdam, Basel and Valetta

                   Target  Distance_km         Duration  Longitude   Latitude
1  Amsterdam, Netherlands         4532   48 hours-3 min   4.904139  52.367573
3      Basel, Switzerland         4092   44 hours-2 min   7.588576  47.559599
2         Valletta, Malta         3792  50 hours-50 min  14.514100  35.899237